# Generated by Django 3.0.2 on 2020-02-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0004_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_by',
            field=models.CharField(choices=[(1, 'Breaktime'), (2, 'Lunchtime')], default=1, max_length=1),
        ),
    ]
